project:
  type: website

website:
  title: "Jingdan Zou"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - papers.qmd
      - posts.qmd
      - cv.qmd


format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

