project:
  type: website

website:
  title: "jingdan_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - papers.qmd
      - about.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

